---
#play 1
- hosts: all
  vars_files:
    - vars_step3.yml
  sudo: yes
  roles:
  - { role: rvm_io.rvm1-ruby, tags: ruby, sudo: True }
  tasks:
  - name: make doc osmium
    command: "make doc chdir=/opt/osmium/"
  - name: make install osmium
    command: "make install chdir=/opt/osmium/"
  - name: make osm-history-splitter
    command: "make chdir=/opt/osm-history-splitter/" 
  - name: add rvm to bashrc
    lineinfile: dest=/home/vagrant/.bashrc line="source /etc/profile.d/rvm.sh"
  - name: clone repo 6
    git: clone=yes repo=https://github.com/google/protobuf dest=/opt/protobuf
  - name: autogen protobuf
    command: "./autogen.sh chdir=/opt/protobuf/"
  - name: configure protobuf
    command: "./configure chdir=/opt/protobuf/"
  - name: make protobuf
    command: "make chdir=/opt/protobuf/"
  - name: make check protobuf
    command: "make check chdir=/opt/protobuf/"
  - name: make install protobuf
    command: "make install chdir=/opt/protobuf/"
  - name: clone repo 7
    git: clone=yes repo=https://github.com/protobuf-c/protobuf-c dest=/opt/protobuf-c
  - name: autogen protobuf
    command: "./autogen.sh chdir=/opt/protobuf-c/"
  - name: configure protobuf
    command: "./configure chdir=/opt/protobuf-c/"
  - name: sudo ldconfig
    command: ldconfig
  - name: make 
    command: "make chdir=/opt/protobuf-c/"
  - name: make install protobuf
    command: "make install chdir=/opt/protobuf-c/"
  - name: change permissions
    file: path=/opt owner=vagrant group=vagrant state=directory recurse=yes
  - name: change permissions
    file: path=/usr/local/rvm owner=vagrant group=vagrant state=directory recurse=yes
  - name: download Google Earth
    get_url: url=http://dl.google.com/dl/earth/client/current/google-earth-stable_current_i386.deb dest=/tmp
#  - name: install lsb-core
#    apt: name=lsb-core state=present
#  - name: de-package Google Earth
#    command: "sudo dpkg -i google-earth-stable_current_i386.deb chdir=/tmp" 
#  - name: install Google Earth
#    command: "sudo apt-get install -f chdir=/tmp" 
#  - name: Install required system packages 2.
#    apt: pkg={{ item }} state=installed update-cache=yes
#    with_items: 
#      - "{{ system_packages }}"

#play 2
- hosts: all
  sudo: no
  gather_facts: no

#look into, failed because of extconf.rb
#  tasks:
#  - name: bundler install
#    command: "bundle install chdir=/opt/osm-history/"

#play 3
- hosts: all
  sudo_user: postgres
  sudo: yes
  gather_facts: no

  tasks:
  - name: create database
    postgresql_db: name=vagrant
  - name: create vagrant postgres user
    postgresql_user: db=vagrant name=vagrant password=vagrant priv=ALL role_attr_flags=CREATEDB,CREATEUSER
  



